version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - nbulaj
  ignore:
  - dependency-name: rubocop-rails_config
    versions:
    - 1.3.0
    - 1.4.2
  - dependency-name: rspec-rails
    versions:
    - 4.1.0
  - dependency-name: rails
    versions:
    - 6.1.2
