name: CI

on: [push, pull_request]

jobs:
  build:
    name: >-
      Ruby ${{ matrix.ruby }}
    env:
      CI: true
      RAILS_ENV: test
      DB: sqlite

    runs-on: ${{ matrix.os }}
    if: |
      !(   contains(github.event.pull_request.title,  '[ci skip]')
        || contains(github.event.pull_request.title,  '[skip ci]'))
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest ]
        ruby:
          - '3.2.0'
    steps:
      - name: Repo checkout
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run tests
        timeout-minutes: 10
        run: bundle exec rake db:setup spec
