# frozen_string_literal: true

source "http://rubygems.org"

ruby "3.1.4"

gem "rails", "~> 7.1"
gem 'activestorage'
gem "doorkeeper", "~> 5.6.9"
gem "devise", "~> 4.9"
gem "sprockets-rails", require: "sprockets/railtie"

gem "faker"
gem "jquery-rails"

gem "coderay"
 gem 'sqlite3', '~> 1.3', '>= 1.3.6'

gem "uglifier"
gem "rollbar"

gem "puma"
gem "rack-timeout"

group :development do
  gem "listen"
  gem "rubocop-performance"
  gem "rubocop-rails_config"
end

group :test do
  gem "rspec-rails"
  gem "factory_bot_rails"
  gem "database_cleaner"
end

group :development, :test do
  gem "pry-rails"
end
